export const initialValue = {
  loadHome: () => {},
  filter: () => {},
  homeData: [],
  filtered: [],
  parameter: "",
  handleChangeParameter: () => {},
  handleClearParameter: () => {},
  handleChangeViewType: () => {},
  setFiltered: () => {},
  viewType: "list",
  currentItems: [],
  setCurrentItems: () => {},
  loading: true,
  setLoading: () => {},
  handleSort: () => {},
  ascSort: false,
  setAscSort: () => {},
  dispatchPagination: false,
  setDispatchPagination: () => {},
};
